export const categoryMapping: Record<string, { label: string; slug: string }> = {
    'crossfit': { label: 'CrossFit & Funcional', slug: 'crossfit' },
    'gym': { label: 'Gimnasios Pesas', slug: 'gimnasios' },
    'balance': { label: 'Balance', slug: 'balance' },
    'artes-marciales': { label: 'Artes Marciales', slug: 'artes-marciales' },
    'boxeo': { label: 'Boxeo', slug: 'boxeo' },
    'raqueta': { label: 'Deportes Raqueta', slug: 'raqueta' },
    'gimnasia': { label: 'Gimnasia', slug: 'gimnasia' },
    'clubes': { label: 'Clubes Deportivos', slug: 'clubes' },
    'acuaticos': { label: 'Acuáticos', slug: 'acuaticos' },
    'baile': { label: 'Baile y Danza', slug: 'baile' },
    'aventura': { label: 'Aventura', slug: 'aventura' },
    'equipo': { label: 'Deportes Equipo', slug: 'equipo' },
    'salud': { label: 'Salud Deportiva', slug: 'salud' },
    'kickboxing': { label: 'Kickboxing', slug: 'kickboxing' },
    'karate': { label: 'Karate', slug: 'karate' },
    'taekwondo': { label: 'Taekwondo', slug: 'taekwondo' },
    'judo': { label: 'Judo', slug: 'judo' },
    'jiu-jitsu': { label: 'Jiu-Jitsu Brasileño', slug: 'jiu-jitsu' },
    'lucha-libre': { label: 'Lucha Libre', slug: 'lucha-libre' },
    'mma': { label: 'MMA', slug: 'mma' },
    'krav-maga': { label: 'Krav Maga', slug: 'krav-maga' },
    'tenis': { label: 'Tenis', slug: 'tenis' },
    'padel': { label: 'Pádel', slug: 'padel' },
    'squash': { label: 'Squash', slug: 'squash' },
    'fronton': { label: 'Frontón/Frontenis', slug: 'fronton' },
    'pickleball': { label: 'Pickeball', slug: 'pickleball' },
    'pinpon': { label: 'Pinpon', slug: 'pinpon' },
    'badminton': { label: 'Bádminton', slug: 'badminton' },
    'zumba': { label: 'Zumba', slug: 'zumba' },
    'ritmos-latinos': { label: 'Ritmos Latinos', slug: 'ritmos-latinos' },
    'pole-dance': { label: 'Pole Dance', slug: 'pole-dance' },
    'aerial': { label: 'Aerial (Telas)', slug: 'aerial' },
    'salsa': { label: 'Salsa', slug: 'salsa' },
    'bachata': { label: 'Bachata', slug: 'bachata' },
    'futbol': { label: 'Futbol', slug: 'futbol' },
    'basquetball': { label: 'Basquetball', slug: 'basquetball' },
    'voleibol': { label: 'Voleibol', slug: 'voleibol' },
    'yoga': { label: 'Yoga', slug: 'yoga' },
    'pilates': { label: 'Pilates', slug: 'pilates' },
    'barre': { label: 'Barre', slug: 'barre' },
    'gap': { label: 'GAP', slug: 'gap' },
    'ciclismo': { label: 'Ciclismo', slug: 'ciclismo' },
    'senderismo': { label: 'Senderismo', slug: 'senderismo' },
    'escalada': { label: 'Escalada', slug: 'escalada' },
    'running': { label: 'Running', slug: 'running' },
    'fisioterapia': { label: 'Fisioterapia / Masajes', slug: 'fisioterapia' },
    'nutricion': { label: 'Nutrición', slug: 'nutricion' },
    // Categorías principales nuevas
    'ecuestres': { label: 'Deportes Ecuestres', slug: 'ecuestres' },
    'precision': { label: 'Precisión y Estrategia', slug: 'precision' },
    'ruedas': { label: 'Deportes Sobre Ruedas', slug: 'ruedas' },
    // Subcategorías Ecuestres
    'equitacion': { label: 'Equitación', slug: 'equitacion' },
    'salto': { label: 'Salto Ecuestre', slug: 'salto' },
    'charreria': { label: 'Charrería', slug: 'charreria' },
    'equinoterapia': { label: 'Equinoterapia', slug: 'equinoterapia' },
    'cabalgatas': { label: 'Cabalgatas', slug: 'cabalgatas' },
    // Subcategorías Precisión y Estrategia
    'tiro-arco': { label: 'Tiro con Arco', slug: 'tiro-arco' },
    'golf': { label: 'Golf', slug: 'golf' },
    'billar': { label: 'Billar Deportivo', slug: 'billar' },
    'boliche': { label: 'Boliche', slug: 'boliche' },
    'ajedrez': { label: 'Ajedrez', slug: 'ajedrez' },
    // Subcategorías Sobre Ruedas
    'patinaje': { label: 'Patinaje', slug: 'patinaje' },
    'skateboarding': { label: 'Skateboarding', slug: 'skateboarding' },
    'bmx': { label: 'BMX', slug: 'bmx' },
    'hockey-ruedas': { label: 'Hockey sobre Ruedas', slug: 'hockey-ruedas' }
};

export function getCategoryData(sanityValue: string) {
    return categoryMapping[sanityValue] || { label: sanityValue, slug: sanityValue };
}
