import { defineField, defineType } from 'sanity'

export const proveedorType = defineType({
    name: 'proveedor',
    title: 'Proveedores',
    type: 'document',
    fields: [
        defineField({
            name: 'order',
            title: 'Orden de aparición',
            description: 'Número para ordenar (ej. 1 para aparecer primero, 2 segundo...)',
            type: 'number',
            initialValue: 100,
        }),
        defineField({
            name: 'name',
            title: 'Nombre del Negocio',
            type: 'string',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'slug',
            title: 'Slug',
            type: 'slug',
            options: {
                source: 'name',
                maxLength: 96,
            },
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'category',
            title: 'Categorías',
            description: 'Selecciona todas las categorías que apliquen',
            type: 'array',
            of: [{ type: 'string' }],
            options: {
                list: [
                    { title: '🏋️ CrossFit & Funcional', value: 'crossfit' },
                    { title: '💪 Gimnasios Pesas', value: 'gym' },
                    { title: '🧘 Balance (Yoga, Pilates, Barre, GAP)', value: 'balance' },
                    { title: '🧘 Yoga', value: 'yoga' },
                    { title: '🧘 Pilates', value: 'pilates' },
                    { title: '🧘 Barre', value: 'barre' },
                    { title: '🧘 GAP', value: 'gap' },
                    { title: '🥋 Artes Marciales (General)', value: 'artes-marciales' },
                    { title: '👊 Kickboxing', value: 'kickboxing' },
                    { title: '🥋 Karate', value: 'karate' },
                    { title: '🥋 Taekwondo', value: 'taekwondo' },
                    { title: '🤼 Judo', value: 'judo' },
                    { title: '🥋 Jiu-Jitsu Brasileño', value: 'jiu-jitsu' },
                    { title: '🤼 Lucha Libre', value: 'lucha-libre' },
                    { title: '⚔️ MMA', value: 'mma' },
                    { title: '⚔️ Krav Maga', value: 'krav-maga' },
                    { title: '🥊 Boxeo', value: 'boxeo' },
                    { title: '🏸 Deportes Raqueta (General)', value: 'raqueta' },
                    { title: '🎾 Tenis', value: 'tenis' },
                    { title: '🏓 Pádel', value: 'padel' },
                    { title: '🎾 Squash', value: 'squash' },
                    { title: '🎾 Frontón/Frontenis', value: 'fronton' },
                    { title: '🏓 Pickeball', value: 'pickleball' },
                    { title: '🏓 Pinpon', value: 'pinpon' },
                    { title: '🏸 Bádminton', value: 'badminton' },
                    { title: '🤸 Gimnasia', value: 'gimnasia' },
                    { title: '🏢 Clubes Deportivos', value: 'clubes' },
                    { title: '🏊 Acuáticos', value: 'acuaticos' },
                    { title: '💃 Baile y Danza (General)', value: 'baile' },
                    { title: '💃 Zumba', value: 'zumba' },
                    { title: '🕺 Ritmos Latinos', value: 'ritmos-latinos' },
                    { title: '💃 Pole Dance', value: 'pole-dance' },
                    { title: '🎪 Aerial (Telas)', value: 'aerial' },
                    { title: '💃 Salsa', value: 'salsa' },
                    { title: '🕺 Bachata', value: 'bachata' },
                    { title: '🚵 Aventura', value: 'aventura' },
                    { title: '🚲 Ciclismo', value: 'ciclismo' },
                    { title: '🥾 Senderismo', value: 'senderismo' },
                    { title: '🧗 Escalada', value: 'escalada' },
                    { title: '🏃 Running', value: 'running' },
                    { title: '⚽ Deportes Equipo (General)', value: 'equipo' },
                    { title: '⚽ Futbol', value: 'futbol' },
                    { title: '🏀 Basquetball', value: 'basquetball' },
                    { title: '🏐 Voleibol', value: 'voleibol' },
                    { title: '🐴 Deportes Ecuestres (General)', value: 'ecuestres' },
                    { title: '🏇 Equitación', value: 'equitacion' },
                    { title: '🐎 Salto Ecuestre', value: 'salto' },
                    { title: '🤠 Charrería', value: 'charreria' },
                    { title: '🐴 Equinoterapia', value: 'equinoterapia' },
                    { title: '🐴 Cabalgatas', value: 'cabalgatas' },
                    { title: '🎯 Precisión y Estrategia (General)', value: 'precision' },
                    { title: '🏹 Tiro con Arco', value: 'tiro-arco' },
                    { title: '⛳ Golf', value: 'golf' },
                    { title: '🎱 Billar Deportivo', value: 'billar' },
                    { title: '🎳 Boliche', value: 'boliche' },
                    { title: '♟️ Ajedrez', value: 'ajedrez' },
                    { title: '🛼 Deportes Sobre Ruedas (General)', value: 'ruedas' },
                    { title: '⛸️ Patinaje', value: 'patinaje' },
                    { title: '🛹 Skateboarding', value: 'skateboarding' },
                    { title: '🚴 BMX', value: 'bmx' },
                    { title: '🏒 Hockey sobre Ruedas', value: 'hockey-ruedas' },
                    { title: '🏥 Salud Deportiva', value: 'salud' },
                    { title: '🏥 Fisioterapia / Masajes', value: 'fisioterapia' },
                    { title: '🏥 Nutrición', value: 'nutricion' },
                ],
            },
            validation: (Rule) => Rule.required().min(1),
        }),
        defineField({
            name: 'description',
            title: 'Descripción',
            type: 'text',
            rows: 4,
        }),
        defineField({
            name: 'address',
            title: 'Dirección (Texto)',
            type: 'string',
        }),
        defineField({
            name: 'mapEmbedUrl',
            title: 'URL de Google Maps (Iframe)',
            description: 'Copia el src del iframe de Google Maps (Share -> Embed Map)',
            type: 'string',
        }),
        defineField({
            name: 'whatsapp',
            title: 'Teléfono (WhatsApp)',
            description: 'Escribir el número con código de país sin el símbolo +, ej: 529511234567',
            type: 'string',
        }),
        defineField({
            name: 'mainImage',
            title: 'Imagen Principal',
            type: 'image',
            options: {
                hotspot: true,
            },
        }),
        defineField({
            name: 'gallery',
            title: 'Galería de Imágenes',
            type: 'array',
            of: [{ type: 'image', options: { hotspot: true } }],
        }),
        defineField({
            name: 'services',
            title: 'Servicios',
            type: 'array',
            of: [{ type: 'string' }],
        }),
        defineField({
            name: 'openingHours',
            title: 'Horarios de Apertura',
            type: 'array',
            of: [
                {
                    type: 'object',
                    title: 'Horario',
                    fields: [
                        { name: 'days', title: 'Días', type: 'string', description: 'Ej. Lunes a Viernes' },
                        { name: 'hours', title: 'Horario', type: 'string', description: 'Ej. 06:00 - 22:00' }
                    ]
                }
            ]
        }),
        defineField({
            name: 'rating',
            title: 'Calificación',
            description: 'Calificación de 1 a 5 (ej. 4.9)',
            type: 'number',
            initialValue: 4.9,
            validation: (Rule) => Rule.min(1).max(5),
        }),
    ],
})
